import { useParams, Link } from "wouter";
import { useTrip } from "@/hooks/use-trips";
import { Loader2, ArrowLeft, Download, Share2 } from "lucide-react";
import { FeasibilityReportView } from "@/components/FeasibilityReport";
import { ItineraryTimeline } from "@/components/ItineraryTimeline";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";

export default function TripDetails() {
  const { id } = useParams();
  const { data: trip, isLoading, error } = useTrip(Number(id));

  if (isLoading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-slate-50">
        <Loader2 className="w-12 h-12 text-primary animate-spin mb-4" />
        <h2 className="text-xl font-display font-semibold text-slate-900">Analyzing Your Trip...</h2>
        <p className="text-slate-500 max-w-md text-center mt-2">
          We're checking 150+ visa policies, live flight prices, and safety advisories for you.
        </p>
      </div>
    );
  }

  if (error || !trip) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-slate-900 mb-2">Trip Not Found</h1>
          <Link href="/">
            <Button variant="link">Go Back Home</Button>
          </Link>
        </div>
      </div>
    );
  }

  const isFeasible = trip.feasibilityStatus === 'yes' || trip.feasibilityStatus === 'warning';

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-40">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/">
              <Button variant="ghost" size="icon" className="rounded-full">
                <ArrowLeft className="w-5 h-5" />
              </Button>
            </Link>
            <div>
              <h1 className="text-lg font-bold font-display text-slate-900">{trip.destination}</h1>
              <p className="text-xs text-slate-500">{trip.dates} • {trip.budget} USD</p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" className="hidden sm:flex">
              <Share2 className="w-4 h-4 mr-2" /> Share
            </Button>
            <Button variant="outline" size="sm" className="hidden sm:flex">
              <Download className="w-4 h-4 mr-2" /> Export
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-5xl">
        {/* Pending State */}
        {trip.feasibilityStatus === 'pending' && (
           <div className="text-center py-20">
             <Loader2 className="w-16 h-16 text-primary animate-spin mx-auto mb-6" />
             <h2 className="text-2xl font-bold mb-2">Finalizing Report</h2>
             <p className="text-muted-foreground">Almost there...</p>
           </div>
        )}

        {/* Report & Itinerary */}
        {trip.feasibilityStatus !== 'pending' && (
          <div className="space-y-12">
            <section>
              <h2 className="text-2xl font-display font-bold text-slate-900 mb-6">Feasibility Report</h2>
              <FeasibilityReportView trip={trip} />
            </section>
            
            {isFeasible ? (
              <motion.section 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.5, duration: 0.8 }}
              >
                <div className="flex items-center justify-between mb-8 border-t border-slate-200 pt-12">
                   <h2 className="text-2xl font-display font-bold text-slate-900">Proposed Itinerary</h2>
                   <div className="text-sm text-muted-foreground">Generated by GPT-5.1</div>
                </div>
                <ItineraryTimeline trip={trip} />
              </motion.section>
            ) : (
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="bg-red-50 border border-red-100 rounded-2xl p-8 text-center mt-12"
              >
                <h3 className="text-xl font-bold text-red-800 mb-2">Itinerary Generation Paused</h3>
                <p className="text-red-600 mb-6">
                  Due to the critical issues identified in the feasibility report, we haven't generated a detailed itinerary yet. 
                  We recommend adjusting your budget or destination.
                </p>
                <Link href="/create">
                   <Button variant="destructive">Adjust Trip Parameters</Button>
                </Link>
              </motion.div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}
